export const matchesSample = [
  {
    husband: "Luella",
    wife: "Amanda",
    husbandProfile: "user6.jpg",
    wifeProfile: "user10.jpg",
    date: "6 months ago",
    couplePics: "couple1.jpg",
  },
  {
    husband: "Claudia",
    wife: "Mary",
    husbandProfile: "user11.jpg",
    wifeProfile: "user13.jpg",
    date: "11 months ago",
    couplePics: "couple2.jpg",
  },
  {
    husband: "Bill",
    wife: "Virgieia",
    husbandProfile: "user17.jpg",
    wifeProfile: "user20.jpg",
    date: "3 months ago",
    couplePics: "couple3.jpg",
  },
  {
    husband: "Adeline",
    wife: "Lora",
    husbandProfile: "user8.jpg",
    wifeProfile: "user15.jpg",
    date: "6 months ago",
    couplePics: "couple4.jpg",
  },
  {
    husband: "Lula",
    wife: "Calebia",
    husbandProfile: "user17.jpg",
    wifeProfile: "user4.jpg",
    date: "4 months ago",
    couplePics: "couple5.jpg",
  },
  {
    husband: "Victor",
    wife: "Edna",
    husbandProfile: "user11.jpg",
    wifeProfile: "user15.jpg",
    date: "7 months ago",
    couplePics: "couple6.jpg",
  },
  {
    husband: "Bobby",
    wife: "Billya",
    husbandProfile: "user15.jpg",
    wifeProfile: "user5.jpg",
    date: "12 months ago",
    couplePics: "couple7.jpg",
  },
  {
    husband: "Leonard",
    wife: "Sally",
    husbandProfile: "user17.jpg",
    wifeProfile: "user16.jpg",
    date: "8 months ago",
    couplePics: "couple8.jpg",
  },
  {
    husband: "Harold",
    wife: "Loretta",
    husbandProfile: "user5.jpg",
    wifeProfile: "user15.jpg",
    date: "6 months ago",
    couplePics: "couple9.jpg",
  },
  {
    husband: "Arthur",
    wife: "Leona",
    husbandProfile: "user9.jpg",
    wifeProfile: "user10.jpg",
    date: "10 months ago",
    couplePics: "couple10.jpg",
  },
];
